name: flatmate_app_v1
description: "FlatMate – shared flat management app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # FlutterFire (Dart 3.8 uyumlu yeni nesil sürümler)
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.3

  # Web interop – PromiseJsImpl / dartify / jsify için şart
  web: ^1.1.0
  js: ^0.7.1

  # UI / charts / media
  pie_chart: ^5.4.0
  fl_chart: ^0.66.1
  image_picker: ^1.0.7

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loogo.png
    
