// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIuDoFjCZFVXSr4px4FL8K0ZvD1sNsfGk',
    appId: '1:204496834874:web:13fd814ead32bc262c0003',
    messagingSenderId: '204496834874',
    projectId: 'flatmateappv1-ff05d',
    authDomain: 'flatmateappv1-ff05d.firebaseapp.com',
    storageBucket: 'flatmateappv1-ff05d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATT7RSlJYYWI4opOUVlk7XRaMi5o9pHIs',
    appId: '1:204496834874:android:6aa943bab5c200502c0003',
    messagingSenderId: '204496834874',
    projectId: 'flatmateappv1-ff05d',
    storageBucket: 'flatmateappv1-ff05d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8HgHdms2FKtvNkyILd5_uxANdyLz_4Wc',
    appId: '1:204496834874:ios:7f3b96923a451e2b2c0003',
    messagingSenderId: '204496834874',
    projectId: 'flatmateappv1-ff05d',
    storageBucket: 'flatmateappv1-ff05d.firebasestorage.app',
    iosBundleId: 'com.example.flatmateAppV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8HgHdms2FKtvNkyILd5_uxANdyLz_4Wc',
    appId: '1:204496834874:ios:7f3b96923a451e2b2c0003',
    messagingSenderId: '204496834874',
    projectId: 'flatmateappv1-ff05d',
    storageBucket: 'flatmateappv1-ff05d.firebasestorage.app',
    iosBundleId: 'com.example.flatmateAppV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIuDoFjCZFVXSr4px4FL8K0ZvD1sNsfGk',
    appId: '1:204496834874:web:369e3dd36458ffb32c0003',
    messagingSenderId: '204496834874',
    projectId: 'flatmateappv1-ff05d',
    authDomain: 'flatmateappv1-ff05d.firebaseapp.com',
    storageBucket: 'flatmateappv1-ff05d.firebasestorage.app',
  );
}
